#!/bin/bash
set -e

echo "Creating Moodle and JupyterHub databases..."

mysql -u root -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE_MOODLE}\`;
    CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE_MOODLE}\`.* TO '${MARIADB_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE_JUPYTERHUB}\`;
    CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE_JUPYTERHUB}\`.* TO '${MARIADB_USER}'@'%';

    FLUSH PRIVILEGES;
EOSQL
