#!/bin/bash
set -e

echo "Creating Moodle and JupyterHub databases..."

mariadb -u root -p"${MARIADB_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE_MOODLE}\`
        CHARACTER SET utf8mb4
        COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE_MOODLE}\`.* TO '${MARIADB_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS \`${MARIADB_DATABASE_JUPYTERHUB}\`
        CHARACTER SET utf8mb4
        COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE_JUPYTERHUB}\`.* TO '${MARIADB_USER}'@'%';

    FLUSH PRIVILEGES;
EOSQL
