version: '3.8'
services:
  jupyterhub:
    image: {{jupyterhub_image}}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - {{jupyterhub_dir}}/jupyterhub:/etc/jupyterhub
      - /exchange:/exchange
      - /jupyter:/jupyter
    networks:
      - {{swarm_network}}
    environment:
      DOCKER_NETWORK_NAME: {{swarm_network}}
      JUPYTERHUB_FQDN: {{jupyterhub_fqdn}}
      DB_USER: {{db_user}}
      DB_PASSWORD: {{db_password}}
      EMAIL_DOMAIN: {{email_domain}}
      JUPYTERHUB_ADMIN_USERS: "{{jupyterhub_admin_users}}"
      CONFIGPROXY_AUTH_TOKEN: {{configproxy_auth_token}}
      TEACHER_GID: {{gid_teacher}}
      STUDENT_GID: {{gid_student}}
      NB_NODE_ROLE: {{node_role}}
      LDAP_ADMIN: {{ldap_admin}}
      LDAP_PASSWORD: {{ldap_password}}
      LTI_METHOD: {{get_course_member_method}}
      LMS_API_TOKEN: {{lms_api_token}}
      HOME_DIR_ROOT: {{home_directory_root}}
      SHARE_DIR_ROOT: {{share_directory_root}}
      NOTEBOOK_IMAGE: {{singleuser_image}}
      LMS_PLATFORM_ID: {{lms_platform_id}}
      LMS_CLIENT_ID: {{lms_cliend_id}}
      LTI_USERNAME_KEY: {{lti_username_key}}
      DEFAULT_URL: {{default_url}}
      JUPYTERHUB_BASE_URL: {{jupyterhub_base_url}}
    command: ["jupyterhub", "-f", "/etc/jupyterhub/jupyterhub_config.py"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  jupyterhub-proxy:
    image: jupyterhub/configurable-http-proxy
    networks:
      - {{swarm_network}}
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      CONFIGPROXY_AUTH_TOKEN: {{configproxy_auth_token}}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  proxy:
    image: nginx:1.24.0
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - {{base_dir}}/jupyterhub/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - {{certs_dir}}/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - {{certs_dir}}/privkey.pem:/etc/nginx/certs/privkey.pem
    networks:
      - {{swarm_network}}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  openldap:
    image: bitnami/openldap:2.5.14
    environment:
      - LDAP_SKIP_DEFAULT_TREE=yes
      #- LDAP_ALLOW_ANON_BINDING=no
      - LDAP_ROOT=dc=jupyterhub,dc=server,dc=sample,dc=jp
      - LDAP_ADMIN_USERNAME={{ldap_admin}}
      - LDAP_ADMIN_PASSWORD={{ldap_password}}
    networks:
      - {{swarm_network}}
    volumes:
      - {{base_dir}}/jupyterhub/ldap/ldifs:/ldifs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  mariadb:
    image: mariadb:10.5.15
    environment:
      MYSQL_ROOT_PASSWORD: {{db_password}}
      MYSQL_USER: {{db_user}}
      MYSQL_PASSWORD: {{db_password}}
      MYSQL_DATABASE: jupyterhub
    networks:
      - {{swarm_network}}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
networks:
  {{swarm_network}}:
    driver: overlay
    name: {{swarm_network}}
{% if moodle_host is defined %}
    attachable: true
{% endif %}
    ipam:
      config:
        - subnet: {{jupyterhub_backend}}
