services:
  selenium-executer:
    container_name: selenium-executer
    image: selenium/standalone-firefox:4.23.1-20240820
    ports:
      - 4444:4444
      - 7900:7900
    environment:
      SE_OPTS: "--sub-path /selenium"
      SE_NODE_MAX_SESSIONS: 100
      SE_NODE_OVERRIDE_MAX_SESSIONS: "true"
    healthcheck:
      test: "curl -f http://localhost:4444/ || exit 1"
      interval: 5s
      retries: 3
  selenium-client:
    container_name: selenium-client
    build:
      context: ./selenium-client
    volumes:
      - type: bind
        source: ./{{ accounts_file }}
        target: /app/{{ accounts_file }}
      - ./selenium-client/result:/app/result
    environment:
      LMS_URL: {{ lms_platform_id }}
      RESULT_OUTPUT: "true"
      CODE_EXEC: "print('Hello world')"
      LMS_TOOL_ID: {{ lms_tool_id }}
      ACCOUNTS_FILE: {{ accounts_file }}
    command: ["python", "/app/test.py", "/app/{{ accounts_file }}"]
    depends_on:
      selenium-executer:
        condition: service_healthy