# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD={{moodle_db_password}}
      - MARIADB_ROOT_PASSWORD={{moodle_db_password}}
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - mm_network
  moodle:
    image: docker.io/bitnami/moodle:4.2.7
    # ports:
    #   - '8080:8080'
     # - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_HOST={{jupyterhub_fqdn}}
      - MOODLE_REVERSEPROXY=true
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD={{moodle_admin_password}}
      - MOODLE_DATABASE_PASSWORD={{moodle_db_password}}
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - mm_network
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
networks:
  mm_network:
    external: true